[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run superapp_dashboard.py --server.port $PORT --server.address 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[environments.production]
variables = { } 